import type { FittingMethod } from '../types/method.types';
import { ROUTES } from '../router/routes';

export const FITTING_METHODS: FittingMethod[] = [
  {
    id: 'linear',
    name: 'Ajuste Lineal',
    shortName: 'Lineal',
    formula: 'y = a + bx',
    formulaLatex: 'y = a + bx',
    description: 'Modelo de regresión lineal simple. Establece una relación proporcional directa entre las variables.',
    category: 'linear',
    status: 'available',
    iconName: 'TrendingUp',
    route: ROUTES.LINEAR,
    variables: ['a', 'b'],
    applicability: 'Datos con tendencia lineal constante.',
  },
  {
    id: 'exponential',
    name: 'Ajuste Exponencial',
    shortName: 'Exponencial',
    formula: 'y = ae^(bx)',
    formulaLatex: 'y = ae^{bx}',
    description: 'Modela crecimientos o decrecimientos exponenciales continuos en fenómenos naturales.',
    category: 'nonlinear',
    status: 'available',
    iconName: 'Activity',
    route: ROUTES.EXPONENTIAL,
    variables: ['a', 'b'],
    applicability: 'Crecimiento poblacional, decaimiento radiactivo.',
  },
  {
    id: 'geometric',
    name: 'Ajuste Geométrico',
    shortName: 'Geométrico',
    formula: 'y = ax^b',
    formulaLatex: 'y = ax^b',
    description: 'Relación de tipo potencial entre variables. Linealizable mediante transformación logarítmica.',
    category: 'nonlinear',
    status: 'available',
    iconName: 'BarChart2',
    route: ROUTES.GEOMETRIC,
    variables: ['a', 'b'],
    applicability: 'Leyes de potencia, alometría biológica.',
  },
  {
    id: 'hyperbolic',
    name: 'Ajuste Hiperbólico',
    shortName: 'Hiperbólico',
    formula: 'y = 1 / (a + bx)',
    formulaLatex: 'y = \\frac{1}{a + bx}',
    description: 'Modela relaciones inversas entre variables con asíntota horizontal.',
    category: 'nonlinear',
    status: 'available',
    iconName: 'Minus',
    route: ROUTES.HYPERBOLIC,
    variables: ['a', 'b'],
    applicability: 'Cinética enzimática, resistencia eléctrica.',
  },
  {
    id: 'asymptotic',
    name: 'Exp. Asintótico',
    shortName: 'Asintótico',
    formula: 'y = a(1 - e^(-bx))',
    formulaLatex: 'y = a(1 - e^{-bx})',
    description: 'Crecimiento limitado que se aproxima a una asíntota. Modela saturación de sistemas.',
    category: 'special',
    status: 'available',
    iconName: 'GitBranch',
    route: ROUTES.ASYMPTOTIC,
    variables: ['a', 'b'],
    applicability: 'Aprendizaje, absorción de fármacos.',
  },
  {
    id: 'logistic',
    name: 'Ajuste Logístico',
    shortName: 'Logístico',
    formula: 'y = L / (1 + e^(-k(x-x₀)))',
    formulaLatex: 'y = \\frac{L}{1 + e^{-k(x-x_0)}}',
    description: 'Curva sigmoidal con crecimiento acelerado seguido de saturación. Modelo de capacidad de carga.',
    category: 'special',
    status: 'available',
    iconName: 'Zap',
    route: ROUTES.LOGISTIC,
    variables: ['L', 'k', 'x₀'],
    applicability: 'Epidemiología, adopción tecnológica.',
  },
  {
    id: 'logarithmic',
    name: 'Ajuste Logarítmico',
    shortName: 'Logarítmico',
    formula: 'y = a + b·ln(x)',
    formulaLatex: 'y = a + b\\ln(x)',
    description: 'Crecimiento desacelerado modelado por función logarítmica natural.',
    category: 'nonlinear',
    status: 'available',
    iconName: 'Layers',
    route: ROUTES.LOGARITHMIC,
    variables: ['a', 'b'],
    applicability: 'Escala de Richter, intensidad sonora.',
  },
  {
    id: 'polynomial',
    name: 'Ajuste Polinomial',
    shortName: 'Polinomial',
    formula: 'y = a₀ + a₁x + … + aₖxᵏ',
    formulaLatex: 'y = a_0 + a_1x + \\cdots + a_kx^k',
    description: 'Regresión polinomial por mínimos cuadrados. Ajusta un polinomio de grado k con ecuaciones normales resueltas por eliminación gaussiana.',
    category: 'nonlinear',
    status: 'available',
    iconName: 'Sigma',
    route: ROUTES.POLYNOMIAL,
    variables: ['a₀', 'a₁', '…', 'aₖ'],
    applicability: 'Datos con curvatura compleja, respuesta al tratamiento, cinética química.',
  },
  {
    id: 'power',
    name: 'Ajuste Potencial',
    shortName: 'Potencial',
    formula: 'y = ax^b',
    formulaLatex: 'y = ax^b',
    description: 'Generalización de la ley de potencia. Ampliamente usado en física y ciencias naturales.',
    category: 'nonlinear',
    status: 'available',
    iconName: 'Cpu',
    route: ROUTES.POWER,
    variables: ['a', 'b'],
    applicability: 'Física, meteorología, economía.',
  },
];

export const getMethodById = (id: string): FittingMethod | undefined =>
  FITTING_METHODS.find(m => m.id === id);
